# Generated by Django 4.2 on 2023-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state_district', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('phone1', models.IntegerField(max_length=100)),
                ('phone2', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=1000)),
            ],
        ),
    ]
