# Generated by Django 4.2 on 2023-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_model',
            name='phone1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration_model',
            name='phone2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
