# Generated by Django 4.2 on 2023-04-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_app', '0002_alter_registration_model_phone1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration_model',
            new_name='Registration',
        ),
    ]
